<?php
/**
 * Created by PhpStorm.
 * User: syg
 * Date: 2017/5/10
 * Time: 15:34
 * job:南农后台人员管理
 */
namespace Admin\Controller;

class BrowBooksManageController extends CommonCtroller
{
    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //订单显示
    public function index(){
        $this->menu  =  ACTION_NAME;
        $library_id  =  1;
        //订单编号,书的标题，isbn号，卷册号，申请人姓名，申请状态,申请时间
        $orderList   =    M('Order_book_list as l')
                    ->join('noto_book as b on b.id=l.book_id')
                    ->join('noto_order as o on o.id=l.order_id')
                    ->join('noto_user as u on u.id=o.user_id')
                    ->field('o.id,b.title,b.isbn,b.volume,u.user_name,o.library_id,l.status,o.create_time')
                    ->where("o.library_id='".$library_id."'")
                    ->select();
        $this->assign('orderList',$orderList);
        $this->display();
    }


}