<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/24
 * Time: 下午8:52
 */

namespace Admin\Controller;


class FileManageController extends CommonController
{
    //文件管理
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //文件管理主界面
    public function index(){
        $this->menu  =  ACTION_NAME;
        //echo "<pre>";
        //print_r(readDirectory('Upload'));
        //die;


        $this->display();
    }
    //获得文件文件夹列表接口
    public function getFileList(){
        echo json_encode(readDirectory('Upload'));
        die;
    }

    //创建文件文件夹接口

    public function createFile(){

        $name=I('get.name');
        $path=I('get.path');
        $act=I('get.act');
        $pathname=$path.'/'.$name;
        $pattern='/[\/\*<>\?\|]/';
        if($act=='createfile'){
            //判断有无特殊字符
            if(!preg_match($pattern,$name)){
                //判断文件名称是否已存在
                if(!file_exists($pathname)){
                    if(touch($pathname)){
                        //创建问价
                        echo json_encode(array('status'=>true,'msg'=>'添加文件成功'));
                        die;

                    }else{
                        echo json_encode(array('status'=>true,'msg'=>'添加文件失败'));
                        die;

                    }

                }else{
                    //文件同名
                    echo json_encode(array('status'=>false,'msg'=>'已存在同名文件'));
                    die;
                }

            }else{
                //文件名非法
                echo json_encode(array('status'=>false,'msg'=>'文件名非法'));
                die;
            }

        }else{
            //添加文件夹
            echo json_encode(array('status'=>true,'msg'=>'添加文件夹成功'));
        }



    }

}