<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/23
 * Time: 下午2:22
 */

namespace Admin\Controller;


class InfoManageController extends CommonController
{
    //资料管理
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //基本信息
    public function index(){
        $this->menu  =  ACTION_NAME;

        $this->display();
    }
    //获得图书馆详细信息接口
    public function getLibraryInfo(){
        $libId=$_COOKIE['ADMIN_LIBID'];
        $libInfo=M('library')->find($libId);
        echo json_encode($libInfo);
        die;

    }
    //馆藏地管理
    public function holding(){
        $this->display();

    }

}