<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/11
 * Time: 下午4:44
 */

namespace Admin\Controller;

/**
 * 权限管理
 * Class RbacController
 * @package Admin\Controller
 */
class RbacController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //添加角色
    public function addRole(){
        $this->menu  =  ACTION_NAME;

        $this->display();
    }
    //角色管理
    public function manageRole(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }
    //添加权限
    public function addNode(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }
    //权限管理
    public function manageNode(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }

    //添加馆员
    public function addAdmin(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }
    //管理官员
    public function manageAdmin(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }

}