<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/11
 * Time: 下午4:44
 */

namespace Admin\Controller;

/**
 * 权限管理
 * Class RbacController
 * @package Admin\Controller
 */
class RbacController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //添加角色
    public function addRole(){
        $this->menu  =  ACTION_NAME;

        $this->display();
    }

    //添加角色异步方法
    public function addRoleHandle(){
        if(M('adminRole')->add($_POST)){
            echo json_encode(array('status'=>true,'msg'=>'添加成功'));
        }else{
            echo json_encode(array('status'=>false,'msg'=>'添加失败'));
        }
        die;
    }
    //角色管理
    public function manageRole(){

        $action=I('get.action');
        //获得roleList接口
        if($action=='getRoleList'){
            $roleList=M('adminRole')->select();
            echo json_encode($roleList);
            die;


        }

        $this->menu  =  ACTION_NAME;
        $this->display();

    }
    //添加权限
    public function addNode(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }
    //权限管理
    public function manageNode(){

        $action=I('get.action');
        $adminNode=M('adminNode');
        //获得nodeList接口
        if($action=='getNodeList'){
            $nodeList=M('adminNode')->select();
            echo json_encode($nodeList);
            die;


        }elseif($action=='getPidNodeList'){
            //获得可以作为父节点的下拉列表
            $nodePidList=M('adminNode')->where(array('level',array('neq 3')))->order('sort')->select();
            echo json_encode($nodePidList);
            die;


        }elseif ($action=='addNode'){

            if($adminNode->add($_POST)){
                echo json_encode(array('status'=>true,'msg'=>'添加成功'));
            }else{
                echo json_encode(array('status'=>false,'msg'=>'添加失败'));
            }
            die;



        }

        $this->menu  =  ACTION_NAME;
        $this->display();

    }

    //添加馆员
    public function addAdmin(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }
    //管理官员
    public function manageAdmin(){

        $this->menu  =  ACTION_NAME;

        $this->display();

    }

}