<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/11
 * Time: 下午6:03
 */

namespace Admin\Controller;


class SystemManageController extends CommonController
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //添加角色
    public function layout(){
        $this->menu  =  ACTION_NAME;

        $this->display();
    }

}