<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/26
 * Time: 下午4:14
 */

namespace Admin\Controller;


class TopicManageController extends CommonController
{
    //专题管理
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
        $this->catename="专题管理";
    }
    //专题列表
    public function index(){
        $this->menu  =  ACTION_NAME;
        $this->menuname="专题列表";
        $this->display();
    }
    //获得专题列表接口
    public function getTopicList(){
        $page=I('get.page');
        $pagesize=I('get.pagesize');
        $start=($page-1)*$pagesize;
        //echo $start;die;
        //$end=$page*$pagesize;
        $totalcount=count(M('topic')->select());

        $result=M('topic')->limit($start,$pagesize)->select();
        echo json_encode(array('result'=>$result,'totalcount'=>$totalcount));
        die;

    }
    //添加专题接口
    public function addTopic(){
        $_POST['createtime']=time();
       if(M('topic')->add($_POST)){
           echo json_encode(array('status'=>true,'msg'=>'插入成功'));
       }else{
           echo json_encode(array('status'=>false,'msg'=>'插入失败'));
       }
       die;

    }
    //删除专题接口
    public function deleteTopic(){
        $id=I('get.id');
        if(M('topic')->where(array('id'=>$id))->delete()){
            echo json_encode(array('status'=>true,'msg'=>'删除成功'));
        }else{
            echo json_encode(array('status'=>false,'msg'=>'删除失败'));
        }
        die();
    }

}