<?php
/**
 * Created by PhpStorm.
 * User: syg
 * Date: 2017/5/10
 * Time: 14:04
 * job:南农后台人员管理
 */
namespace Admin\Controller;
class UserManageController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }
    //申请用户显示
    public function index(){
        $this->menu=ACTION_NAME;

        $searchValue  =   trim(I('post.searchValue'));
        if($searchValue){
            $where = "u.card='".$searchValue."' or u.user_name='".$searchValue."' or u.phone='".$searchValue."'";
        }
        //显示的第几页
        $page        =     intval($_GET['page'])?$_GET['page']:1;
        $min         =     ($page-1)*1;
        //共有几页
        $count       =     M('User as u')->where($where)->count();
        $page_count  =     ceil($count/1);
        $this->assign('page_count',$page_count);
        $this->assign('page',$page);

        $user    =    M('User as u')
                ->join('noto_user_detail as d on u.id=d.user_id','LEFT')
                ->order('create_time desc')
                ->where($where)
                ->limit($min,1)
                ->select();
        $this->assign('user',$user);
        $this->display();
    }
    //馆员操作
    public function exam(){
        $this->menu=ACTION_NAME;
        if(IS_POST){
            $id     =   intval(I('post.id'));
            $state  =   intval(I('post.state'));
            $where  =   "id='".$id."'";
            $data['state']   =   $state;
            $res    =    M('User')->data($data)->where($where)->save();
            if ($res) {
                $return['code']    =    200;
                $return['msg']     =    '操作成功！';
            } else {
                $return['code']    =    400;
                $return['msg']     =    '操作失败！';
            }
        }else{
            $return['code']    =    400;
            $return['msg']     =    '操作失败！';
        }
        $this->ajaxReturn($return);exit;

    }

    //一键审核
    public function  pass(){
        $this->menu=ACTION_NAME;
        $arrId   =   I('post.arrId');
        if($arrId == null || empty($arrId)){
            $return['code']    =    400;
            $return['msg']     =    '请先选择人员！';
            $this->ajaxReturn($return);
        }
        $arrId   =   explode(',',$arrId);
        foreach($arrId as $key=>$value){
            $data['state'] = 2;
            $where  =  "id='".$value."'";
            M('User')->data($data)->where($where)->save();
        }
        foreach($arrId as $k=>$v){
            $user['state'] = M('User')->where(array('id'=>$v))->getField('state');
            if($user['state'] != 2){
                $return['code']    =    400;
                $return['msg']     =    '操作失败！';
            }else{
                $return['code']    =    200;
                $return['msg']     =    '操作成功！';
            }

        }

        $this->ajaxReturn($return);exit;
    }

}