<?php
/**
 * Created by PhpStorm.
 * User: daivd
 * Date: 2017/5/9
 * Time: 下午7:22
 */

namespace Admin\Controller;
use Think\Controller;


class UserManageController extends Controller
{
    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }


    public function index(){//用户列表2git fansongweilaile ingnore
        $this->menu=ACTION_NAME;

        $this->display();
    }

}